#!/usr/bin/env python
"""Generate ``eeo/core/core.pyi`` from ``core.py`` plus the decorator registry.

``EEORasterDataset`` gains most of its methods dynamically: every function
decorated with ``@eeo_raster_op`` / ``@eeo_raster_viz`` is bound onto the class
at import time (see ``eeo/core/decorators.py``). Those methods are invisible to
type checkers and IDEs, so a single stub, ``eeo/core/core.pyi``, re-declares the
full public surface of the class.

Because a ``.pyi`` shadows its ``.py`` entirely for type checkers, the stub must
contain *both* the class's own methods (parsed from ``core.py``) and the
dynamically bound operations (read from the decorator registry). This script
merges the two and writes the result, normalised with ``ruff format``.

Usage
-----
    python scripts/generate_core_stub.py            # write the stub
    python scripts/generate_core_stub.py --check     # exit 1 if the stub is stale

The stub is never edited by hand; a freshness check (see
``tests/test_stub_freshness.py`` and CI) enforces that it matches this script's
output.
"""

from __future__ import annotations

import argparse
import ast
import copy
import inspect
import subprocess
import sys
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CORE_PY = REPO_ROOT / "eeo" / "core" / "core.py"
CORE_PYI = REPO_ROOT / "eeo" / "core" / "core.pyi"
CLASS_NAME = "EEORasterDataset"

# Always generate from the working-tree ``eeo``, not an installed copy that may
# be stale or shadow the repo when this script runs from ``scripts/``.
sys.path.insert(0, str(REPO_ROOT))

# Decorators kept on the class's own methods when rendering the stub. Anything
# else is dropped.
_KEEP_DECORATORS = {"property", "classmethod", "staticmethod"}

# Curated import header. The stub references types by the exact text of each
# source annotation, so every name used in an annotation must resolve here.
# ``CRS`` is rasterio's (used by ``get_crs`` / ``from_array``); reproject's
# pyproj CRS is written qualified as ``pyproj.CRS`` in its source annotation to
# avoid a name clash. When a new op introduces a new type, add its import here
# (mypy in CI will flag a missing one).
HEADER = """\
# This file is auto-generated by scripts/generate_core_stub.py -- DO NOT EDIT.
#
# It re-declares the full public surface of EEORasterDataset for type checkers,
# including the methods bound dynamically by the @eeo_raster_op / @eeo_raster_viz
# decorators. Regenerate after adding or changing a bound op or a core.py method:
#     python scripts/generate_core_stub.py
from collections.abc import Iterable, Sequence

import geopandas as gpd
import numpy as np
import pyproj
import rasterio as rio
from affine import Affine
from rasterio import CRS
from rasterio.coords import BoundingBox
from rasterio.enums import Resampling

from eeo.analysis.stats import Coordinate
from eeo.core.adapters import BaseRasterAdapter
from eeo.core.types import ResamplingMethod
"""


def _ellipsis() -> ast.expr:
    return ast.Constant(value=...)


def _stubify(func_def: ast.FunctionDef, *, drop_first: bool) -> ast.FunctionDef:
    """Return a copy of ``func_def`` reduced to a stub declaration.

    The body becomes ``...``, every default becomes ``...``, and (for bound
    ops) the leading dataset parameter is replaced by ``self``.
    """
    node = copy.deepcopy(func_def)
    node.body = [ast.Expr(value=_ellipsis())]

    # All defaults collapse to ``...`` (stub convention); required keyword-only
    # params keep their ``None`` slot in kw_defaults so they stay required.
    node.args.defaults = [_ellipsis() for _ in node.args.defaults]
    node.args.kw_defaults = [None if d is None else _ellipsis() for d in node.args.kw_defaults]

    if drop_first:
        # Bound op: drop the leading dataset arg, prepend ``self``, and shed the
        # binding decorator (@eeo_raster_op / @eeo_raster_viz).
        if node.args.posonlyargs:
            node.args.posonlyargs = node.args.posonlyargs[1:]
        elif node.args.args:
            node.args.args = node.args.args[1:]
        else:  # pragma: no cover - defensive; every op takes a dataset first
            raise ValueError(f"{node.name!r} has no leading dataset parameter")
        node.args.args = [ast.arg(arg="self", annotation=None), *node.args.args]
        node.decorator_list = []
    else:
        node.decorator_list = [
            d for d in node.decorator_list if isinstance(d, ast.Name) and d.id in _KEEP_DECORATORS
        ]

    return node


def _instance_attrs(class_def: ast.ClassDef) -> list[ast.AnnAssign]:
    """Declare instance attributes assigned from annotated ``__init__`` params.

    A ``.pyi`` replaces the ``.py`` for type checkers, and stub bodies are ``...``
    -- so ``self._adapter = adapter`` in ``__init__`` no longer exposes the
    attribute. Re-declare each ``self.x = param`` (where ``param`` is annotated)
    as a class-level ``x: <annotation>`` so code like ``ds._adapter`` still
    type-checks.
    """
    init = next(
        (n for n in class_def.body if isinstance(n, ast.FunctionDef) and n.name == "__init__"),
        None,
    )
    if init is None:
        return []

    param_annotations = {a.arg: a.annotation for a in init.args.args if a.annotation is not None}
    attrs: list[ast.AnnAssign] = []
    seen: set[str] = set()
    for stmt in init.body:
        if not (isinstance(stmt, ast.Assign) and len(stmt.targets) == 1):
            continue
        target = stmt.targets[0]
        if not (
            isinstance(target, ast.Attribute)
            and isinstance(target.value, ast.Name)
            and target.value.id == "self"
        ):
            continue
        if not (isinstance(stmt.value, ast.Name) and stmt.value.id in param_annotations):
            continue
        if target.attr in seen:
            continue
        seen.add(target.attr)
        attrs.append(
            ast.AnnAssign(
                target=ast.Name(id=target.attr, ctx=ast.Store()),
                annotation=copy.deepcopy(param_annotations[stmt.value.id]),
                value=None,
                simple=1,
            )
        )
    return attrs


def _own_methods() -> list[ast.FunctionDef]:
    return [
        _stubify(n, drop_first=False) for n in _class_def().body if isinstance(n, ast.FunctionDef)
    ]


def _class_def() -> ast.ClassDef:
    module = ast.parse(CORE_PY.read_text())
    return next(n for n in module.body if isinstance(n, ast.ClassDef) and n.name == CLASS_NAME)


def _bound_ops() -> list[ast.FunctionDef]:
    import eeo  # noqa: F401  (import triggers decorator registration)
    from eeo.core.decorators import _OP_REGISTRY

    ops: dict[str, ast.FunctionDef] = {}
    for func, _kind in _OP_REGISTRY:
        source = textwrap.dedent(inspect.getsource(func))
        func_def = next(n for n in ast.parse(source).body if isinstance(n, ast.FunctionDef))
        ops[func.__name__] = _stubify(func_def, drop_first=True)
    return [ops[name] for name in sorted(ops)]


def generate() -> str:
    # Parse an empty class template rather than constructing ClassDef directly,
    # so every AST field the running Python version expects (e.g. type_params on
    # 3.12+) is present without version-specific handling.
    module = ast.parse(f"class {CLASS_NAME}: ...")
    class_def = module.body[0]
    assert isinstance(class_def, ast.ClassDef)
    class_def.body = [*_instance_attrs(_class_def()), *_own_methods(), *_bound_ops()]
    ast.fix_missing_locations(module)
    raw = f"{HEADER}\n{ast.unparse(module)}\n"
    return _ruff_format(raw)


def _ruff_format(text: str) -> str:
    result = subprocess.run(
        ["ruff", "format", "--stdin-filename", str(CORE_PYI), "-"],
        input=text,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed stub differs from freshly generated output",
    )
    args = parser.parse_args()

    generated = generate()
    if args.check:
        current = CORE_PYI.read_text() if CORE_PYI.exists() else ""
        if generated != current:
            print(
                f"{CORE_PYI.relative_to(REPO_ROOT)} is out of date. "
                "Regenerate with: python scripts/generate_core_stub.py",
                file=sys.stderr,
            )
            return 1
        return 0

    CORE_PYI.write_text(generated)
    print(f"Wrote {CORE_PYI.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
